version: '3.8'
services:
  llm:
    build:
      context: .
      dockerfile: Dockerfile
    image: bureaucratschoice/dckr_vector_service:0.1
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "80:80"